apiVersion: apps/v1
kind: Deployment
metadata:
  name: beachcomb-deployment
  labels:
    app: beachcomb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beachcomb
  template:
    metadata:
      labels:
        app: beachcomb
    spec:
      containers:
        - name: beachcomb
          image: europe-west3-docker.pkg.dev/dse24-group-12/dse-repo/beachcomb_service:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /beachcomb/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /beachcomb/health
              port: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://dse24:HaB1glbuEZRkO9kw@cluster0.cjccyax.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service.default
            - name: SPRING_RABBITMQ_PASSWORD
              value: secret
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
